### ISSUE TITLE
Inputs not registering while Left and Up held?

### ISSUE THREAD

**Issue by samhay18** [tesselode/baton#23]
This is a super weird bug and I've done plenty of testing to figure out what is going wrong and I'm completely stuck. Whenever I press the "left" and "up" arrow keys together they are the only inputs that will work. This is any key that is added into baton as a control like action or quit. Even weirder is lets say I have action on the "g" key bound, if I use love.keyboard.isDown("g") while "left" and "up" are pressed it returns false. I can switch move left to be bound to the "right" arrow key and the same error occurs of no inputs during "left" and "up" arrow keys being down.
I've added a line during the function sourceFunction.keyboardMouse.key to print out the key and the results but same issue of it returning false when I know its down.
I've copied the exact configs from the demo and tested it and no error there and I'm at a loss as to what is causing it. 
This is also without the callbacks version but I don't see why that would be an issue.

**Comment by tesselode** [comment]
Without knowing more about your situation, I'm guessing that your keyboard just doesn't support pressing certain combinations of 3 or more keys at once. A lot of keyboards are like that (see [here](https://en.wikipedia.org/wiki/Rollover_(key))). You can also try printing `love.keyboard.isDown` for three different keys to see if LOVE can even detect all the keypresses.

If this isn't the issue, let me know, because then there is more investigation afoot!
